"""empty message

Revision ID: 254d1ea47dcc
Revises: f7b8512cb00c
Create Date: 2023-03-11 16:48:19.135866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '254d1ea47dcc'
down_revision = 'f7b8512cb00c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student', sa.Integer(), nullable=True),
    sa.Column('course', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('letter_grade', sa.String(length=1), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course'], ['courses.id'], name=op.f('fk_grades_course_courses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student'], ['students.id'], name=op.f('fk_grades_student_students'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_grades')),
    sa.UniqueConstraint('student', 'course', name=op.f('uq_grades_student'))
    )
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credit_unit', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_column('credit_unit')

    op.drop_table('grades')
    # ### end Alembic commands ###
