"""empty message

Revision ID: 5c3084c3c6d1
Revises: e513a9eab48a
Create Date: 2023-03-11 18:17:31.467435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c3084c3c6d1'
down_revision = 'e513a9eab48a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('student_no',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.alter_column('teacher_no',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.alter_column('teacher_no',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('student_no',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###
