"""empty message

Revision ID: 639b200c04b2
Revises: fba212051ba9
Create Date: 2023-03-13 09:23:32.301440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '639b200c04b2'
down_revision = 'fba212051ba9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_course', schema=None) as batch_op:
        batch_op.drop_constraint('fk_student_course_student_id_students', type_='foreignkey')
        batch_op.drop_constraint('fk_student_course_course_id_courses', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_student_course_student_id_students'), 'students', ['student_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_student_course_course_id_courses'), 'courses', ['course_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_course', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_student_course_course_id_courses'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_student_course_student_id_students'), type_='foreignkey')
        batch_op.create_foreign_key('fk_student_course_course_id_courses', 'courses', ['course_id'], ['id'])
        batch_op.create_foreign_key('fk_student_course_student_id_students', 'students', ['student_id'], ['id'])

    # ### end Alembic commands ###
