"""empty message

Revision ID: 67cb874e534b
Revises: 639b200c04b2
Create Date: 2023-03-13 09:34:11.194023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67cb874e534b'
down_revision = '639b200c04b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_course', schema=None) as batch_op:
        op.execute("DELETE FROM student_course WHERE course_id=1")
        batch_op.create_unique_constraint(batch_op.f('uq_student_course_student_id'), ['student_id', 'course_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_course', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_student_course_student_id'), type_='unique')

    # ### end Alembic commands ###
