"""empty message

Revision ID: e513a9eab48a
Revises: 254d1ea47dcc
Create Date: 2023-03-11 16:50:41.282352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e513a9eab48a'
down_revision = '254d1ea47dcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit', sa.Integer(), nullable=True))
        batch_op.drop_column('credit_unit')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credit_unit', sa.INTEGER(), nullable=True))
        batch_op.drop_column('unit')

    # ### end Alembic commands ###
